### ISSUE TITLE
Set up SonarQube

### ISSUE THREAD

**Issue by badgerwithagun** [alfasoftware/morf#15]
Would be good to get some metrics up on the public project.

**Comment by wnicholson** [comment]
Agree. Let's get [`coverage-per-test`](https://github.com/SonarSource/sonar-examples/tree/master/projects/languages/java/code-coverage/ut/ut-maven-jacoco) set up in the build too so we can see it in Sonar.

**Comment by badgerwithagun** [comment]
@venushka, @wnicholson, is this done? We still have #32 and #31 open as separate issues.

**Comment by venushka** [comment]
Yes, coverage-per-test is working fine. The code coverage information on https://sonarcloud.io provides information about which test(s) covered the code now.
