### ISSUE TITLE
Fix javadoc errors

### ISSUE THREAD

**Issue by venushka** [alfasoftware/morf#17]
There's a lot of JavaDoc errors in the build, all these needs fixing and fail on JavaDoc error needs to be enabled on the build by removing the failOnError = false flag on parent pom.xml

**Comment by badgerwithagun** [comment]
Note that these are a major contributor to the need to pipe our build output to /dev/null.

See PR #35

**Comment by badgerwithagun** [comment]
Fixed by #33
