### ISSUE TITLE
Findbugs excluding J2EE_STORE_OF_NON_SERIALIZABLE_OBJECT_INTO_SESSION probably inappropriate

### ISSUE THREAD

**Issue by badgerwithagun** [alfasoftware/morf#19]
I doubt this is even needed this low in the stack anyway, but it makes a big assumption.  Should try and remove this exclusion.

**Comment by badgerwithagun** [comment]
See https://github.com/alfasoftware/morf/blob/master/findbugs-exclude.xml#L58

**Comment by tsg21** [comment]
Agreed, this definitely isn't needed. Morf has no awareness of the Servlet API anyway.
