### ISSUE TITLE
Findbugs excluding JCIP_FIELD_ISNT_FINAL_IN_IMMUTABLE_CLASS probably inappropriate

### ISSUE THREAD

**Issue by badgerwithagun** [alfasoftware/morf#20]
See https://github.com/alfasoftware/morf/blob/master/findbugs-exclude.xml#L14

Pretty sure we can just remove this

**Comment by tsg21** [comment]
Yes, that's not relevant to Morf.

**Comment by badgerwithagun** [comment]
Done.
