### ISSUE TITLE
TestXmlDataSetConsumer.testIndexOrdering() failing due to line delimiters mismatching

### ISSUE THREAD

**Issue by badgerwithagun** [alfasoftware/morf#27]
`org.alfasoftware.morf.xml.TestXmlDataSetConsumer.testIndexOrdering()` fails on my personal machine with the two strings mismatching.  They look identical when compared but have a different `.length()`.  I converted the `testIndexOrdering.xml` file to Unix line endings, and the test passes.

I could submit a PR with [this change](https://github.com/badgerwithagun/morf/commits/fixlf) but there must be a reason why this is failing on my machine and not elsewhere.

Thoughts?

**Comment by venushka** [comment]
I think when we serialise XMLs to disk, we only use line endings and not carriage returns `\r`. This test is comparing the serialised version with the XML file in the repo, which is rightly has only line break `\n` characters.

It doesn't fail on mine, so I presume you might have set your [core.autocrlf](https://help.github.com/articles/dealing-with-line-endings/) enabled on your machine. I would really recommend switching it off if this is the case, the VCS shouldn't really change any files based on OS/settings on client, the files checked out must be identical to what's in the repo really.

**Comment by tsg21** [comment]
Looks like we could ensure this works everywhere by using a `.gitattributes` file.

**Comment by tsg21** [comment]
Possible fix: #41

**Comment by badgerwithagun** [comment]
@tsg21 : OK, this has made things even worse.  Now our internal repo and the GitHub master have mismatching linefeeds. I can't change the internal repo to match GitHub or our tests fail.

Is it possible that `testIndexOrdering()` is generating XML based on local-specific linefeeds?  That would mean that when run on Windows it needs to compare with CRLF, but when run on *Nix it needs to compare with LF.

Something not quite right about that explanation, but I'm a bit run ragged at the moment...

**Comment by badgerwithagun** [comment]
@tsg21 , I assume this can now be closed?

**Comment by tsg21** [comment]
Yes. If the tests are passing (they are) and nobody's complaining about local issues (they aren't) we might as well close this one.
