### ISSUE TITLE
Investigate SonarQube incremental analysis -> GitHub plugin for PRs

### ISSUE THREAD

**Issue by wnicholson** [alfasoftware/morf#31]
We _might_ be able to use the [the SonarQube -> GitHub plugin](https://docs.sonarqube.org/display/PLUG/GitHub+Plugin) for auto-analysing PRs before merging. It already has Travis support but might need something set up on SonarCloud,io which we isn't available.

Let's see...

**Comment by venushka** [comment]
I think is implemented by 9c7dc7d526c3acc10b1ff237b2ebb848b10ee4da. Please see the comments on the commit.
Also #65 would probably improve the SonarCloud experience by enriching the content published.

**Comment by badgerwithagun** [comment]
Great. Let's close this off and open PRs for any fixes if they're needed.
