### ISSUE TITLE
SonarQube doesn't look like it's counting tests in morf-integrationtest towards the coverage figures

### ISSUE THREAD

**Issue by badgerwithagun** [alfasoftware/morf#32]
Much of the SQL DSL is tested in aggregate over a compile-time choice of database platform by the integration test module.  This is because it's not enough to just prove that it works over an in-memory H2 database - the tests need to be runnable over any platform.

However, it look to me as if this cross-module testing approach isn't counting towards "coverage".

**Comment by badgerwithagun** [comment]
https://docs.sonarqube.org/display/PLUG/Code+Coverage+by+Integration+Tests+for+Java+Project

**Comment by wnicholson** [comment]
Yep - we need to set up the IT coverage as part of the analysis.

We need follow the [Code Coverage by Integration Tests for Java Project](https://docs.sonarqube.org/x/egEW) guide (note the links to their examples are broken - see [this one for an example POM](https://github.com/SonarSource/sonar-scanning-examples/blob/master/sonarqube-scanner-maven/app-it/pom.xml).

**Comment by wnicholson** [comment]
I'm going to attack this one tomorrow morning.

**Comment by badgerwithagun** [comment]
Awesome!
