### ISSUE TITLE
Pipe Maven output to build artifact

### ISSUE THREAD

**Issue by badgerwithagun** [alfasoftware/morf#36]
Pull request #35 piped mvn output to /dev/null. Would be more useful if we could see these as a build artifact.   Travis instructions here https://docs.travis-ci.com/user/uploading-artifacts/ (requires S3).

**Comment by venushka** [comment]
Given we can now see the build log in the console, the only content we would not have are the test logs. With the build time for Morf being just few minutes, its really easy run the build locally if we are investigating a test failure, so I guess this is very low priority or probably even unnecessary at this time?

**Comment by badgerwithagun** [comment]
Unassigning due to lack of progress

**Comment by badgerwithagun** [comment]
Ugh, I assumed it'd be like CircleCI.

Yes, fine.
