### ISSUE TITLE
Remove SqlDialect.buildAutonumberUpdate() and SqlDialect.buildSpecificAutonumberUpdate()

### ISSUE THREAD

**Issue by jsimlo** [alfasoftware/morf#49]
These methods are not suited for a general-purpose library.
This is related to another Alfa product and does not belong here.
Planning to remove them from morf.

**Comment by badgerwithagun** [comment]
Approved.  Go ahead @jsimlo.

**Comment by badgerwithagun** [comment]
Fixed
