### ISSUE TITLE
Remove XML handling, Xalan, XPP3 dependencies from morf-core

### ISSUE THREAD

**Issue by badgerwithagun** [alfasoftware/morf#5]
XML handling is a non-core feature and requires dependencies which should be optional. They should be moved to a separate module, like the `DatabaseType`s.

**Comment by tsg21** [comment]
Hmmm. While I agree it's not core in the strict sense, I do think the XML storage is a pretty essential element. It's like to be pretty essential for much of the testing framework, for example.

Still, it would be nice to remove xpp3.

**Comment by badgerwithagun** [comment]
My thinking is that while the idea of streaming a database into/out of a serialised format *is* core, the choice of doing so to XML is not.

Other choices include compressed bytestreams, JSON or any number of alternatives.  XML is an option. That's fine, but as an option it should be a plugin.

**Comment by tsg21** [comment]
Yes, I understand the thinking, but I wonder if it's decomposition taken too far? We pulled the different DB types out into their own modules because they come with hefty dependencies. I think we can probably re-code the `XmlDataSetProducer` to use `javax.xml.stream.XMLStreamReader` (from core Java) instead of xpp3. If we can do that, is the extraction still worthwhile? I'm not convinced it is - the code is going to be pretty minimal.

**Comment by badgerwithagun** [comment]
The complete list of XML related dependencies includes xalan, xpp3 and xmlpull. If we could redesign to avoid all three dependencies, then that would sort out my primary concern.

My secondary concern is whether any APIs in this area are overly specific to XML as an output format, forcing us into a position where we would have to break compatibility in the future in order to introduce an abstraction, which seems pretty inevitable if someone wants/needs a different format.

That is, I would agree, not a strong enough reason to make the 1.0.0 milestone, but a good enough reason to leave this open in case someone feels like tackling it.

**Comment by badgerwithagun** [comment]
Incidentally, @venushka already pulled out the Excel stuff into a separate submodule with very little difficulty. Instinctively, this should be just as easy. Less effort than trying to refactor it to use a different parser would be.

**Comment by tsg21** [comment]
It's very easy. The API it used to use has essentailly been adopted as the core [StAX standard](https://docs.oracle.com/javase/tutorial/jaxp/stax/why.html)

See branch: remove-xpp3

**Comment by badgerwithagun** [comment]
Sweet. Looks good. Definitely solves the main problem.

I still think this belongs in a side API rather than the core one for maintenance reasons, but I'll have a play with that and see if it can be done without much friction.

**Comment by badgerwithagun** [comment]
Yeah, just as easy:

https://github.com/badgerwithagun/morf/commit/3108c7931d62d770f4eaae0071d8224887d696b8

**Comment by badgerwithagun** [comment]
Do both?

**Comment by tsg21** [comment]
I'm not convinced there's value. It just makes it a bit more fiddly to use with only a trivial benefit in terms of dependency sizing.

**Comment by badgerwithagun** [comment]
OK. At this point I don't mind hugely. Let's get a casting vote and at the very least get your branch in, or both.

**Comment by tsg21** [comment]
Fixed by #40
