### ISSUE TITLE
Introduce the concept of recoverable exceptions into Morf

### ISSUE THREAD

**Issue by JFL110** [alfasoftware/morf#52]
In a similar vein to Hibernate's [JDBCExceptionHelper](https://docs.jboss.org/hibernate/orm/3.5/api/org/hibernate/exception/JDBCExceptionHelper.html) and [org.hibernate.dialect.Dialect.buildSQLExceptionConversionDelegate](http://docs.jboss.org/hibernate/orm/5.1/javadocs/org/hibernate/dialect/Oracle8iDialect.html) it would be great to have a mechanism which can indicate to upstream processing that an exception that has been thrown _probably_ has a recoverable cause and that the operation may be successful if retried. 

The specific case I'm interest in are ORA-02049 and other deadlock exceptions which can be thrown as driver specific OracleXAExceptions or as normal SqlExceptions. 

I propose to introduce a simple RecoverableException wrapper and some dialect-specific exception-classifying logic.

**Comment by badgerwithagun** [comment]
Thanks for raising this, @JFL110.

JDBC already provides for this in the form of exceptions which extend `java.sql.SQLTransientException`.  AFAICT Oracle is just a bad player in not extending this (or indeed using the proper hierarchy of SQL exceptions at all).

Perhaps that's what we should do?

**Comment by JFL110** [comment]
Nice @badgerwithagun, `java.sql.SQLTransientException` sounds like exactly what I'm after.

**Comment by JFL110** [comment]
API wise I think we can either go for, 

`Exception SqlDialect.reclassifyException(Exception exception)`
or (but with a better name)
`boolean SqlDialect.needsWrappingAsTransientException(Exception exception)`

What are your thoughts @badgerwithagun?

**Comment by badgerwithagun** [comment]
@JFL110 , I assume this is already in and the issue can be closed?

**Comment by JFL110** [comment]
@badgerwithagun yep this is in and can be closed.
