### ISSUE TITLE
Remove invalid 'append' Oracle hint

### ISSUE THREAD

**Issue by franksloan** [alfasoftware/morf#54]
The hint 'append' can be removed from our parameterised _INSERT INTO_ statements, this will be ignored by oracle when executed. The [Oracle guide](https://docs.oracle.com/cd/E11882_01/server.112/e41084/sql_elements006.htm#SQLRF50901) states that:

> The APPEND hint instructs the optimizer to use direct-path INSERT with the subquery syntax of the INSERT statement.

Even though APPEND_VALUES is the correct hint for this type of insert it is not appropriate here and would only have performance benefits when executed within a PL/SQL operation.

**Comment by badgerwithagun** [comment]
Pushed to master
