### ISSUE TITLE
Publish snapshots to oss.sonatype.org

### ISSUE THREAD

**Issue by badgerwithagun** [alfasoftware/morf#56]
We're a little way off publishing releases, but not having builds available for developers to pull in using Maven is preventing anyone playing with it (myself included ;)).

Shall we set up on sonatype and deploy there?

Alternatively you can self-host on Github: https://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github

**Comment by badgerwithagun** [comment]
@venushka @wnicholson thoughts?

**Comment by venushka** [comment]
Actually I wanted to do this as soon as we got morf on to Github :)

Its actually quite simple to do, the instructions are here: http://central.sonatype.org/pages/ossrh-guide.html

Code wise, we'll need to put back the <distributionManagement> and <scm> blocks back in to the POMs with the appropriate URLs, and we can get Git **master** builds to publish snapshots with every build.

Releases are just a bit more work, I haven't done one of those in Travis, but we can give this a go when we have a repository to publish to. When we publish a release, it needs to be published to a **staging** repository, and promoting it to **release** repository is a manual step from the Nexus UI after we confirm that what we've built is correct. So we can safely try out building releases without actually releasing.

**Comment by wnicholson** [comment]
Agreed. We'll need to apply for a namespace ({{org.alfasoftware}}?) and comply with http://central.sonatype.org/pages/requirements.html.

**Comment by badgerwithagun** [comment]
Anyone fancy pushing that forward?

**Comment by venushka** [comment]
I can look at the making the project compliant with the requirements and getting it to publish.

@wnicholson, would you mind creating the JIRA project and requesting our namespace from Sonatype as mentioned on http://central.sonatype.org/pages/ossrh-guide.html?

**Comment by wnicholson** [comment]
(finally) done - with Sonatype to check & approve: https://issues.sonatype.org/browse/OSSRH-42285

**Comment by badgerwithagun** [comment]
@venushka : this has been approved. What's next?
