### ISSUE TITLE
RecordHelper.javaTypeToRecordValue(Object) should use toPlainString() for BigDecimal instances

### ISSUE THREAD

**Issue by michal-morzywolek** [alfasoftware/morf#57]
The javadoc of `javaTypeToRecordValue` says: 

> Take a java value (...) and convert it into a string format suitable for inclusion in a {@link Record}

Currently the method uses `toString()` which is not the best idea for `BigDecimal `instances. The `toString `javadoc of `BigDecimal `says:

> Returns the string representation of this BigDecimal, using scientific notation if an exponent is needed.

This means that not only the result returned might be using scientific notation but it's also not used in some cases (the result format may vary). As discussed with @badgerwithagun this is not suitable implementation of a conversion to database format.

The implementation of `javaTypeToRecordValue `should be changed to use `toPlainString`() if the given object is a `BigDecimal `instance. The decimal will be always represented without exponent which is generally desired format for database records.

**Comment by badgerwithagun** [comment]
Yup :thumbsup:

**Comment by badgerwithagun** [comment]
Pushed to master
