### ISSUE TITLE
Use Sonatype DepShield for scanning for vulnerabilities

### ISSUE THREAD

**Issue by venushka** [alfasoftware/morf#63]
We should scan the dependencies we use with Sonatype [DepSheild](https://github.com/marketplace/sonatype-depshield).

**Comment by venushka** [comment]
@wnicholson, would you mind authorising the install of this for the organisation?

**Comment by wnicholson** [comment]
I like the look of that - if we’re signing up on behalf of Alfa then I’ll need to get GitHub and Sonatype Ts & Cs checked.

**Comment by venushka** [comment]
We'll have to signup as Alfa. Would you mind getting the ball rolling? It's not urgent at all, more of a nice to have at the moment.

**Comment by wnicholson** [comment]
All fine for Alfa, app installed & connected.

...but they say our build failed - see #76
