### ISSUE TITLE
Authorise SonarCloud access to Github

### ISSUE THREAD

**Issue by venushka** [alfasoftware/morf#65]
When we so the SonarCloud scan, we get a warning in SonarCloud saying,

> Pull request decoration did not happen. Please install SonarCloud Github application on the repository's organization or user

![image](https://user-images.githubusercontent.com/4840772/47860881-813a4c00-dde9-11e8-9184-9f5ea227b4f2.png)

Seems like they have changed the integration, @wnicholson can you please authorise this as the organisation admin?

**Comment by wnicholson** [comment]
Athe integration’s now a GitHub application - https://github.com/apps/sonarcloud

It’s now authorised to Morf.

**Comment by venushka** [comment]
Seems like this has broken pull request scanning as it seems like its not setting up the sonarscanner in the environment after enabling this. @wnicholson, would you mind disabling this for a bit to see if this was definitely the cause?
Reading a bit more, it seems like this only works for 'internal' pull requests, so it won't actually add any value to pull requests from forks, so if removing this fixes it, i think we can just live with the warning.

**Comment by venushka** [comment]
After a painful process realised that it was nothing to do with this. The tests I did was for internal PRs and they all work, external PRs doesn't work (and that's limitation as per their documentation).

The warning for internal PRs seems to have worked, so let's leave this enabled.

@wnicholson, @badgerwithagun, given this is the case, I guess we'll need to merge PRs from forks in to an internal branch, then do a PR to master from there to get the code scanned. We could do this for changes that might have a significant risk of breaking things than every change so that we just don't create too much work for each change?

I'm closing this now as this is as far as we can go with PR analysis.

**Comment by venushka** [comment]
And, thanks @wnicholson for getting the application authorised :)
